export const Roles = {
  SUPER_ADMIN:'SUPER_ADMIN',
  SUPPORT:'SUPPORT',
  ADMIN:'ADMIN',
  SUPERVISOR:'SUPERVISOR',
  COORDINADOR:'COORDINADOR',
  CAJERO:'CAJERO',
  MESERO:'MESERO',
  GUEST:'GUEST',
};
